config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :blogposts do
    resources :comments
  end
  resources :users

  root 'static_pages#landing_page'

  get 'static_pages/landing_page'

  get '/about', to: 'static_pages#about'

  get '/contact', to: 'static_pages#contact'

  post 'static_pages/thank_you'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
        if user.admin?
           can :manage, :all
        else
            can :read, :all
        end
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blogpost.rb
class Blogpost < ApplicationRecord
  has_many :comments
  def self.search(search_term)
    if Rails.env.development?
      Blogpost.where("name LIKE ?", "%#{search_term}%")
    else
      Blogpost.where("name ilike?", "%#{search_term}%")
    end
  end 
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :blogpost
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_url, :alert => exception.message
  end
end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_blogpost, only: [:show, :edit, :update, :destroy]

  # GET /blogposts
  # GET /blogposts.json
  def index
    if params[:q]
      search_term = params[:q]
      @blogposts = Blogpost.search(search_term)
    else
      @blogposts = Blogpost.all
    end
  end

  # GET /blogposts/1
  # GET /blogposts/1.json
  def show
    @comments = @blogpost.comments.order("created_at DESC")
  end

  # GET /blogposts/new
  def new
    @blogpost = Blogpost.new
  end

  # GET /blogposts/1/edit
  def edit
  end

  # POST /blogposts
  # POST /blogposts.json
  def create
    @blogpost = Blogpost.new(blogpost_params)

    respond_to do |format|
      if @blogpost.save
        format.html { redirect_to @blogpost, notice: 'Blogpost was successfully created.' }
        format.json { render :show, status: :created, location: @blogpost }
      else
        format.html { render :new }
        format.json { render json: @blogpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogposts/1
  # PATCH/PUT /blogposts/1.json
  def update
    respond_to do |format|
      if @blogpost.update(blogpost_params)
        format.html { redirect_to @blogpost, notice: 'Blogpost was successfully updated.' }
        format.json { render :show, status: :ok, location: @blogpost }
      else
        format.html { render :edit }
        format.json { render json: @blogpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogposts/1
  # DELETE /blogposts/1.json
  def destroy
    @blogpost.destroy
    respond_to do |format|
      format.html { redirect_to blogposts_url, notice: 'Blogpost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blogpost
      @blogpost = Blogpost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blogpost_params
      params.require(:blogpost).permit(:name, :description, :image_url, :date)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @blogpost = Blogpost.find(params[:blogpost_id])
    @comment = @blogpost.comments.new(comment_params)
    @comment.user = current_user
    @comment.save
    redirect_to blogpost_path(@blogpost)
  end

  def destroy
  end


  private

    def comment_params
      params.require(:comment).permit(:user_id, :body)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def landing_page
    @blogposts = Blogpost.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  load_and_authorize_resource

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogposts/_blogpost.html.erb
<div class="container">
  <div class="row">
    <% @blogposts.each do |blogpost| %>
      <div class="col-md-12">
        <%= image_tag(blogpost.image_url, class: "img-responsive") %>
        <h1><%= blogpost.name %></h1>
        <p><%= blogpost.description %></p>
        <p><%= blogpost.date %></p>
        <p><%= link_to 'Show', blogpost %> <%= link_to 'Destroy', blogpost, method: :delete, data: { confirm: 'Are you sure?' } %></p>
      </div><!-- /col -->
    <% end %>
  </div>
</div>

app/views/blogposts/_comments.html.erb
<div class="blogpost-reviews">
    <% @comments.each do |comment| %>
        <div class="row">
            <hr>
            <p><%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small></p>
            <p><%= comment.body %></p>
        </div>
    <% end %>
</div>

app/views/blogposts/_form.html.erb
<%= form_for(blogpost) do |f| %>
  <% if blogpost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blogpost.errors.count, "error") %> prohibited this blogpost from being saved:</h2>

      <ul>
      <% blogpost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :image_url %>
    <%= f.text_field :image_url %>
  </div>

  <div class="field">
    <%= f.label :date %>
    <%= f.text_field :date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogposts/_new_comment.html.erb
<% if signed_in? %>
  <h4>Leave a comment:</h4>
  <%= form_for([@blogpost, @blogpost.comments.build]) do |f| %>
    <p>
      <%= f.label :body, "Comment" %><br>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.label :first_name %><br>
      <%= f.text_field :first_name %>
    </p> 
    <p>
      <%= f.label :last_name %><br>
      <%= f.text_field :last_name %>
    </p>  
    <p>
      <%= f.submit "Submit" %>
    </p>
  <% end %>
<% end %>

app/views/blogposts/edit.html.erb
<div class="container">
  <h1>Editing Blogpost</h1>

  <%= render 'form', blogpost: @blogpost %>

  <%= link_to 'Show', @blogpost %> |
  <%= link_to 'Back', blogposts_path %>
</div>

app/views/blogposts/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Blogposts</h1>
    <div class="row">
      <%= render @blogposts %>
    </div>

  <br>

  <%= link_to 'New Blogpost', new_blogpost_path %>
</div>

app/views/blogposts/new.html.erb
<div class="container">
  <h1>New Blogpost</h1>

  <%= render 'form', blogpost: @blogpost %>

  <%= link_to 'Back', blogposts_path %>
</div>

app/views/blogposts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container blogpost">
  <div class="row">
    <div class="col-md-8 col-xs-12">
      <p><span class="glyphicon glyphicon-time"></span> <%= @blogpost.date %></p>
      <h1><%= @blogpost.name %><h1>
      <hr>
      <%= image_tag(@blogpost.image_url, class: "img-responsive detail") %>
      <hr>
      <p><%= @blogpost.description %></p>
      <hr>
    </div>

    <div class="col-md-4 col-xs-12">
      <!-- Blog Search -->
      <div class="well">
          <%= form_tag("/blogposts", method: "get") do %>
          <h4><%= label_tag(:q, "Blog Search") %></h4>
          <div class="input-group">
              <%= text_field_tag(:q, nil, class: "form-control") %>
              <span class="input-group-btn">
                  <%= button_tag("Go", class: "btn btn-default") %>
              </span>
          </div><!-- /input-group -->
          <% end %>
      </div>
    </div>
  </div><!-- /row -->

<%= link_to 'Edit', edit_blogpost_path(@blogpost) %> |
<%= link_to 'Back', blogposts_path %>

</div><!-- /container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>

<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="static_pages/landing_page">Blog</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "home", root_path %></li>  
        <li><%= link_to "articles", blogposts_path %></li>
        <li><%= link_to "about", about_path %></li>
        <li><%= link_to "contact", contact_path %></li>        
      </ul>
      <ul class="nav pull-right">
        <li>
        <% if user_signed_in? %>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
        <% else %>
          <%= link_to('Login', new_user_session_path) %>
        <% end %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

    <!-- Flash notice -->
    <% if notice %> 
      <p id="notice" class="alert alert-success"><%= notice %></p>
    <% end %>

    <%if alert %>
      <p id="alert" class="alert alert-success"><%= alert %></p>
    <% end %>

    <div class="page-wrap">
      <%= yield %>
    </div>

    <!-- Footer -->
    <footer class="site-footer">
      <div class="container">
        Copyright &copy; 2017 Fanny Caloz
      </div>
    </footer>
  </body>
</html>

app/views/static_pages/about.html.erb
<div class="container">
<h1>About Me</h1>
    <h2>Introduction</h2>
    <p>Hello! Thank you for checking my portfolio. I hope that you will find useful information about me and my work. I do all sorts of things, from marketing to web development. I am passionnate about creating beautiful websites and I would love to hear about your project!</p>
    
  <h2>My Skills</h2>
      <ul id="skill-list">
          <li>Social Media Marketing</li>
          <li>Email Marketing</li>
          <li>Content Marketing</li>
          <li>Web development</li>
        </ul>
  
  <h3>My Story</h3>
      <p>After graduating in Communication Sciences and Economics, I decided to work for startups. Since then, I've had different experiences that led among others to jobs in project management, digital marketing, PR and communication. Being passionnate about creating content for websites, I've always missed the technical aspect of it, which is why I am working on web development skills. My goal is to create new websites and be able to edit them. Currently, I am running a coliving and coworking business in Switzerland where I welcome location independent people to work and live together.</p>
</div>

app/views/static_pages/contact.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">

      <h1>Contact me!</h1>
      <%= flash[:notice] %>

      <%= form_tag("/static_pages/thank_you") do %>
      <div class="row">
        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :name %>
            <%= text_field_tag :name, nil, class: "form-control", placeholder: "Your Name" %>
          </div>      
          <div class="form-group">
            <%= label_tag :email, "Email Address" %>
            <%= text_field_tag :email, nil, class: "form-control", placeholder: "Your Email" %>
          </div>
          <div class="form-group">
            <%= label_tag :message %>
            <%= text_area_tag :message, nil, class: "form-control", placeholder: "Your Message" %>
          </div>      
        </div>
      </div>
      <%= submit_tag "Send" %>   
      <% end %>
    </div><!-- /col -->

  </div><!-- /row -->
</div><!-- /container -->

app/views/static_pages/landing_page.html.erb
<!-- Page Content -->
<div class="container">

    <div class="row">


        <!-- Blog Entries Column -->
        <div class="col-md-8">

            <h1 class="page-header">Latest Articles</h1>
                <% @blogposts.each do |blogpost| %>
                    <h2><%= blogpost.name %></h2>
                    <p><span class="glyphicon glyphicon-time"></span> Posted <%= blogpost.date %></p>
                    <hr>
                    <%= image_tag(blogpost.image_url, class: "img-responsive") %>
                    <hr>
                    <p><%= blogpost.description %></p>
                    <a class="btn btn-primary" href="#">Read More <span class="glyphicon glyphicon-chevron-right"></span></a>
                    <hr>
                <% end %>

                <!-- Pager -->
                <ul class="pager">
                    <li class="previous">
                        <a href="#">&larr; Older</a>
                    </li>
                    <li class="next">
                        <a href="#">Newer &rarr;</a>
                    </li>
                </ul>

            </div>

            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">

                <!-- Blog Search -->
                <div class="well">
                    <%= form_tag("/blogposts", method: "get") do %>
                    <h4><%= label_tag(:q, "Blog Search") %></h4>
                    <div class="input-group">
                        <%= text_field_tag(:q, nil, class: "form-control") %>
                        <span class="input-group-btn">
                            <%= button_tag("Go", class: "btn btn-default") %>
                        </span>
                    </div><!-- /input-group -->
                    <% end %>
                </div>

                <!-- Side Widget Well -->
                <div class="well">
                    <h4>About Me</h4>
                    <hr>
                    <p>Hello! Thank you for checking my portfolio. I hope that you will find useful information about me and my work. I do all sorts of things, from marketing to web development. I am passionnate about creating beautiful websites and I would love to hear about your project!</p>
                </div>

            </div>

        </div>
    </div> <!-- end container -->

app/views/static_pages/thank_you.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <p>Thank you. We have received your message and will respond as soon as possible.</p>
  </div><!-- / panel-body -->
</div><!-- / panel -->

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>